title: Git Common Flow
description: >
  An attempt to gather a sensible selection of the most common usage patterns of
  git into a single and concise specification.
author: Jim Myhrberg
url: https://commonflow.org

current_version: 1.0.0-rc.1
versions:
  - 1.0.0-rc.1

update:
  body_tpl: |
    ---
    title: {{title}}
    version: {{version}}
    ---
    {{content}}
  url_tpl: "https://raw.githubusercontent.com/jimeh/common-flow/{{version}}/{{file}}"
  img_tpl: "<img src=\"/spec/{{file}}\" width=\"100%\" />"
  output_dir: "spec"
  files:
    document: common-flow.md
    diagram: common-flow.svg

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
kramdown:
  input: Pantsdown # disable smart quotes typographic symbols
