title: Git Common Flow
description: >
  An attempt to gather a sensible selection of the most common usage patterns of
  git into a single and concise specification.
author: Jim Myhrberg
hostname: commonflow.org
url: https://commonflow.org
repo_url: https://github.com/jimeh/common-flow

current_version: 1.0.0-rc.4
versions:
  - 1.0.0-rc.4
  - 1.0.0-rc.3
  - 1.0.0-rc.2
  - 1.0.0-rc.1

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

update:
  body_tpl: |
    ---
    title: {{title}}
    version: {{version}}
    ---
    {{content}}
  url_tpl: "https://github.com/jimeh/common-flow/raw/{{version}}/{{file}}"
  img_tpl: "<img src=\"/spec/{{file}}\" width=\"100%\" />"
  output_dir: "spec"
  files:
    document: common-flow.md
    diagram: common-flow.svg

plugins:
  - jekyll-assets
  - jekyll-pants
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tidy

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

assets:
  digest: true
  compress:
    css: true
    js: true

markdown: kramdown
kramdown:
  input: Pantsdown # disable smart quotes typographic symbols
