title: Git Common Flow
description: >
  An attempt to gather a sensible selection of the most common usage patterns of
  git into a single and concise specification.
author: Jim Myhrberg

versions:
  - 1.0.0-draft.10

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
